### ISSUE TITLE
Add "Join our Monthly Community Webinars" badge to readme

### ISSUE THREAD

**Issue by balotofi** [BIRDSOpenSource/BIRDS5-Source_Codes#2]
Please find how it is done ideally in popular open source orgs.

Replace the hyperlink in the top of the readme with a more visually appealing badge.

**Comment by sanskriti2005** [comment]
Hello! Is it alright if I work on this? I find this repository to be really interesting and would love contribute :)

**Comment by balotofi** [comment]
Most definitely, your contribution would be most welcome

**Comment by balotofi** [comment]
we're trying to renovate all the repositories right now, give them a good facelift to encourage others, I will continue to add issues to this and other repositories in this organisation that you might find interesting to complete

**Comment by balotofi** [comment]
to keep all readmes of all repos looking uniform, they will have the same structure, if you can just copy the same badge here  https://github.com/BIRDSOpenSource/BIRDS3-ProceduresAndReports that would be great

**Comment by sanskriti2005** [comment]
Thank you! I will work on this then, and would love to contribute more.
